connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *connection
  database: one_auth_client_development
  password: <%= ENV['database_password'] %>

test:
  <<: *connection
  database: one_auth_client_test
  password: <%= ENV['database_password'] %>

production:
  <<: *connection
  database: one_auth_client_production  
  password: <%= ENV['database_password'] %>